.github/workflows/flake8.yml

Связоно: #11
* Исправили валидацию кода через flake8.

fix: Исправил валидацию flake8

---

requirements.txt

* Добавил flake8 в список зависимостей.

build: Добавил flake8 в requirements.txt

---

docker-compose.yml

* Добавлен файл docker-compose в корень проекта

Файл docker-compose

---

.github/workflows/flake8.yml
project/manage.py

Test patch 1

---

.github/workflows/flake8.yml
project/manage.py

36 _логированиее

---

project/core/settings.py

Добавил начальные конфигурации логирования в файл setting.py
Связано: #36
* Добавил начальные конфигурации логирования

feat: Добавил начальные конфигурации логирования

---

apps/web/urls.py
apps/web/views/home/views.py
core/settings.py
core/urls.py
static/css/bootstrap.css
static/css/sidebars.css
static/css/style.css
static/js/bootstrap.js
static/js/jquery.js
static/js/sidebars.js
templates/base.html
templates/home.html
templates/partials/sidebar.html

* Добавил настройку статики в файл конфигурации
* Написал базовый шаблон
* Создал шаблон главной страницы
* Создал в приложении web urls.py
* Сделал include в общий urls.py
* Написал view для главной страницы

feat: Написал главную страницу

---

infrastructure/urls.py
infrastructure/web/service/views.py
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/service/import.html

Реализовала экспорт прайс листа в Exel, с выбором расширения xlsx, xls, csv
Связано:#61
* Реализовать экспорт прайс листа

feat: Реализовать экспорт прайс листа в Exel

---

core/urls.py
infrastructure/web/service/views.py
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/service/import.html
infrastructure/web/templates/service/list.html

* Изменен путь главной страницы на org/1
* А так же все пути от org/1

fix: Исправить пути урл

---

infrastructure/urls.py
infrastructure/web/nomenclature/forms.py
infrastructure/web/nomenclature/views.py
infrastructure/web/templates/nomenclature/nomenclature_create.html
infrastructure/web/templates/partials/nomenclature/nomenclature_form.html
infrastructure/web/templates/partials/sidebar.html
services/nomenclature_services.py

* Реализовано создание номенклатуры
* Добавлена страница создания номенклатуры

feat: Реализовала создание номенклатуры

---

infrastructure/web/own/forms.py
infrastructure/web/own/views.py
infrastructure/web/templates/own/own_create.html
infrastructure/web/templates/partials/own/own_form.html
infrastructure/web/urls.py
services/own_services.py

* Добавила возможность создания собственности у контрагента

feat: реализовала создание собственности

---

infrastructure/web/contractor/forms.py
infrastructure/web/contractor/views.py
infrastructure/web/nomenclature/forms.py
infrastructure/web/templates/contractor/contractor_create.html
infrastructure/web/templates/partials/contractor/contractor_form.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/urls.py
models/own/admin.py
services/contractor_services.py

* Реализовал создание контрагента

feat: Реализовал добавление контрагента

---

infrastructure/web/contractor/views.py
infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/templates/contractor/contractors.html
infrastructure/web/urls.py
services/contractor_services.py
services/organization_services.py

Прописал роуты. Описал логику страницы контрагента. Добавил методы в organization_services.py. Создал шаблоны. Указал ссылки.
Связано: #107
* Добавлено функционал детального просмотра страницы контрагента.

feat: Реализовал детальный просмотр страницы контрагента

---

infrastructure/web/templates/contractor/contractor_detail.html
models/own/models.py

*  Реализовано отображение списка собственности контрагента на странице его детального просмотра

feat: реализовала отображение списка собственности на странице контрагента

---

infrastructure/web/contractor/views.py
infrastructure/web/service/forms.py
infrastructure/web/templates/contractor/contractor_create.html
infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/templates/partials/contractor/contractor_form.html
infrastructure/web/trade_point/forms.py
services/contractor_services.py

* Доработал форму создания контрагента
* Отрефакторил код

123 Доработал форму создания контрагента

---

Dockerfile

* Добавлен Dockerfile в корень проекта.

feat: Добавить Dockerfile

---

.github/workflows/flake8.yml

* исправлены отступы в файле для совместимости с мастером

исправление конфликта

---

models/contractor/admin.py
models/contractor/models.py

Заменил поле 'bank_requisition' на 3 отдельных поля: БИК, номер банковского счёта, наименование банка в модели контрагента
Связано #147

feat: Изменил модель контрагента

---

Dockerfile

* Добавлено команда для обновления pip
* Добавлено команда для запуска приложения

fix: Исправил настройки Dockerfile

---

infrastructure/web/static/css/style.css
infrastructure/web/static/js/services/nomenclature_services.js
infrastructure/web/templates/base.html

* Задал фиксированную позицию сайдбару .

fix: Задал фиксированную позицию сайдбару

---

infrastructure/web/nomenclature/views.py
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/trade_point/trade_points.html
infrastructure/web/trade_point/views.py
infrastructure/web/urls.py
services/trade_point_services.py

* Добавлена страница списка торговых точек.

feat: Добавить страницу списка торговых точек

---

infrastructure/web/templates/contractor/contractor_detail.html

* Отредактировал детальную страницу контрагента

fix: Отредактировал вывод детальной страницы контрагента

---

infrastructure/web/contractor/views.py
infrastructure/web/static/js/contractor/contractor_create.js
infrastructure/web/templates/contractor/contractor_create.html
infrastructure/web/templates/partials/contractor/contractor_form.html
services/organization_services.py

Реализовал отображение данных в полях 'ФИО' и 'Комментарий' доверенного лица после возврата формы. Реализовал сокрытие полей 'ИИК' 'Название банка' 'БИК' после попытки создания физ.лица с вводом невалидных данных.
Связано #171

fix: Отредактировал вывод данных на странице создания контрагента

---

models/order/models.py

* Восстановил поле fk связью с моделью торговой точки у модели заказ-наряда

fix: Добавил поле fk к модели торговой точки

---

core/celery.py
infrastructure/web/nomenclature/tasks.py
infrastructure/web/nomenclature/views.py
infrastructure/web/templates/nomenclature/list.html
infrastructure/web/templates/nomenclature/partial/export.html
infrastructure/web/urls.py
services/nomenclature_services.py

* Исправила bug при скачивании exel файла, добавила celery progress для уведомления о 100% загрузке

fix: Исправить bug при скачивании exel файла

---

celery.sh
infrastructure/web/nomenclature/tasks.py
infrastructure/web/templates/nomenclature/list.html
infrastructure/web/templates/nomenclature/partial/export.html

* Отредактировать баг скачать exel с celery при первом запуске, так же добавила скрипт запуска celery с режимом debug, отредактировала js код

fix: Отредактировать баг скачать exel с celery при первом запуске

---

services/tests/test_order_services.py

feat: Написал тест по заказ-наряду

---

services/tests/test_nomenclature_services.py

* Написать тест на создание номенклатуры

feat: Написать тест на создание номенклатуры

---

services/tests/test_trade_point_services.py

* Написал тесты на сервисы моделей торговой точки

feat: Написать тесты на сервисы моделей торговой точки

---

core/urls.py
infrastructure/accounts/urls.py
infrastructure/accounts/views.py
infrastructure/web/order/views.py
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/registration/login.html
infrastructure/web/urls.py

Связано: #243
* Добавил LoginRequiredMixin на главную страницу
* При запуске приложения все начинается со страницы авторизации

feat: Добавил LoginRequiredMixin на главную страницу

---

infrastructure/web/employee/serializers.py
infrastructure/web/employee/views.py
infrastructure/web/static/js/employee/employee_view.js
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/employee/employees.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/urls.py
services/employee_services.py

Связано: #246
* Добавлено функционал просмотра списка сотрудников по филиалам с возможностью поиска по имени, фамилии, иин или номеру телефона

feat: реализован просмотр списка сотрудников по филиалам с поиском

---

infrastructure/web/templates/nomenclature/list.html
services/nomenclature_services.py

* Исправить баг при импорте exel файла, с наименованием "price - 2022-06-01T201501.688.xlsx

fix: Исправить баг при импорте exel файла

---

services/order_services.py
services/tests/test_order_services.py

Обновил метод create_order в сервисах заказ-наряда после изменения модели, добавив поле jobs
Связано: #268

feat: Написал тесты на все сервисы модели заказ-наряда

---

infrastructure/web/employee/views.py
infrastructure/web/templates/employee/employee_create.html
infrastructure/web/templates/partials/employee/employee_form.html
infrastructure/web/templates/registration/register.html

Связано: #277
* Исправил баг при создании мастера

fix: Исправить баг при создании мастера

---

.github/workflows/docker_hub.yml
.github/workflows/test.yml
core/settings.py
docker-compose.yml
nginx/default.conf

* Убрал из github action запуск на миграцию при проверке на тесты.

283 убрать из action test миграцию

---

core/settings.py
docker-compose.prod.yml
docker-compose.yml

* Добавил в настройках docker-compose.prod.yml сервис wathctower для отслеживания контейнера нашего приложения.

feat: Добавить docker-compose.yml для автопоставки на сервер

---

infrastructure/web/contractor/views.py
services/contractor_services.py

Описал логику метода post класса ContractorUpdate в контроллере.
В файл сервисов конрагента добавил метод get_contractor_by_id_for_update для получения конкретного контрагента с блокировкой парарллельных запросов
Связано: #291

fix: Реализовал пессимистичную блокировку для параллельного обновления данных контрагента

---

.gitignore
infrastructure/web/own/views.py
infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/templates/partials/own/own_form.html

* В контроллере обработал возврат формы с ошибками при создании собственности без указания названия авто
* В шаблонах обработал вывод данных вместо None если не указан авто
* Ошибки формы вывел красным цветом
* Добавил данные в .gitignore

293 Исправил форму создания собственности

---

core/settings.py
docker-compose.prod.yml
docker-compose.yml

* отредактировал докер-компос.

fix: Отредактировал настроки докер-компос

---

.github/workflows/docker_hub_celery.yml
core/celery.py
docker-compose.prod.yml

* Добавил в watchtower отслеживание контейнера celery
* Заменил загрузку образа celery из dockerhub
* Добавил action на обновление образа celery при мердж рекуесте на ветку мастер

feat: Добавить action на обновление образа celery

---

nginx/default.conf

* Добавлено доменное имя в настройки nginx.conf.

fix: Добавил домееное имя в nginx.conf

---

core/celery.py

fix: Изменил env файл

---

Dockerfile

* исправил билд образа проекта для поставки на сервер

fix: исправил билд образа проекта для поставки на сервер

---

docker-compose.prod.yml
nginx/default.conf

* Отредактировал docker-compose.prod.yml для поставки на сервер.

fix: Изменил docker-compose.prod.yml для поставки на сервер

---

infrastructure/web/static/css/style.css
infrastructure/web/static/js/own/own_delete.js
infrastructure/web/templates/contractor/contractor_detail.html

* Переместил кнопки в верхнюю часть
* Выделил название страницы
* Наименование контрактора вписал в карточку данных
* Выполнил валидацию пустых полей

fix: Подкорректировать детальную страницу контрактора

---

core/celery.py
core/settings.py
docker-compose.prod.yml
nginx/default.conf

* Изменил настройки celery для правильной сборки образа приложения.

fix: Отредактировать настройки celery

---

infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/templates/order/order_detail.html

* Переместил кнопки в верхнюю часть
* Выделил название страницы
* Наименование контрактора вписал в карточку данных
* Выполнил валидацию пустых полей

fix: Отредактировать страницу детального просмотра заказ-наряда

---

.github/workflows/docker_hub_celery.yml
core/settings.py

* Разделил на разные файлы ci для сборки образов приложения и celery, а также добавил условие для ci

fix: Отредактировать CI для сборки образа в dockerhub

---

.github/workflows/docker_hub.yml
.github/workflows/docker_hub_celery.yml
core/settings.py

*изменил условие на создание образа в github action

349 отредактировать ci для сборки образа в dockerhub

---

docker-compose.prod.yml
docker-compose.yml

fix: исправил порты для nginx

---

core/settings.py

* Добавлено разрешение на csrf для домена

fix: добавил разрешение на доменное имя

---

core/settings.py
infrastructure/web/nomenclature/tasks/export_exel.py
infrastructure/web/nomenclature/tasks/import_exel.py
infrastructure/web/nomenclature/views.py
requirements.txt
services/nomenclature_services.py

* Добавить кэширование в редис на Export exel

feat: Добавить кэширование в редис на Export exel

---

.github/workflows/docker_hub_celery.yml
core/settings.py
docker-compose.prod.yml
nginx/default.conf

watchtower docker compose

---

.github/workflows/docker_hub_celery.yml
core/settings.py
docker-compose.prod.yml
nginx/default.conf

мастер дев 13

---

docker-compose.prod.yml
entrypoint.sh
init-letsencrypt.sh
nginx/Dockerfile
nginx/default.conf

мастер дев 17

---

core/settings.py

мастер дев 18

---

core/settings.py

мастер дев 19

---

core/settings.py

Добавить кэш хост env

---

core/settings.py

мастер дев 20

---

core/settings.py

fix: изменил настройки кеша для celery в settings.py

---

.github/workflows/docker_hub.yml
.github/workflows/docker_hub_celery.yml

мастер дев 22

---

.github/workflows/docker_hub.yml
.github/workflows/docker_hub_celery.yml
apply-migrations.sh

407 доработать action на проверку тестов и ci на пуш образов

---

infrastructure/web/nomenclature/tasks/export_exel.py
infrastructure/web/nomenclature/tests/test_nomenclature_tasks.py

* Написать тест на tasks import и export file

feat: Написать тест на tasks import и export file

---

.github/workflows/docker_hub.yml
.github/workflows/docker_hub_celery.yml
infrastructure/web/nomenclature/tasks/export_exel.py
infrastructure/web/nomenclature/tests/test_nomenclature_tasks.py

мастер дев 26

---

.github/workflows/docker_hub_celery.yml

мастер дев 27

---

.github/workflows/docker_hub.yml
.github/workflows/docker_hub_celery.yml
infrastructure/web/employee/views.py
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/partials/employee/employee_form.html

мастер дев 28

---

.github/workflows/docker_hub_celery.yml
services/trade_point_services.py

мастер дев 29

---

.github/workflows/docker_hub_celery.yml
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/partials/employee/employee_form.html
services/trade_point_services.py

мастер дев 30

---

.github/workflows/docker_hub_celery.yml
infrastructure/web/templates/employee/employee_detail.html

мастер дев 31

---

.github/workflows/docker_hub_celery.yml
infrastructure/web/templates/employee/employee_detail.html

мастер дев 32

---

.github/workflows/docker_hub_celery.yml

мастер дев 33

---

.github/workflows/docker_hub_celery.yml

мастер дев 34

---

.github/workflows/docker_hub_celery.yml
infrastructure/web/static/css/admin.css
models/employee/models.py
templates/admin/base_site.html

мастер дев 37

---

.github/workflows/docker_hub_celery.yml
.github/workflows/test.yml
infrastructure/web/employee/views.py

мастер дев 38

---

core/settings.py

fix: изменил настройки локации для кеша для продакшна

---

core/settings.py
nginx/default.conf

fix: измменил настройки корса для домена

---

infrastructure/web/static/js/contractor/contractor_view.js
infrastructure/web/static/js/employee/employee_view.js
infrastructure/web/static/js/order/order_create_stage1.js
infrastructure/web/static/js/order/order_list.js
infrastructure/web/static/js/own/own_delete.js
infrastructure/web/static/js/services/nomenclature_services.js
infrastructure/web/templates/base.html

*  Реализовал автогенерацию хоста во всех ajax запросах.

fix: Реализовал автогенерации хоста во всех ajax запросах

---

infrastructure/web/templates/contractor/update.html

Связано: #489
* Добавил кнопку вернуться к списку контрагентов
* Заголовок "Имя банка" переименовал в "Наименование банка"

refactor: Произвёл коррекцию страницы редактирования контрагента

---

infrastructure/web/static/js/own/own_delete.js
infrastructure/web/templates/contractor/contractor_detail.html

Свзано: #493
* Заменил текст в кнопке "Вернуться к списку" на "К списку"
* Заменил заголовок "Список собственностей" заменить на "Список автомобилей"
* В случаях когда отсутствуют собственности у контрагента выводится сообщение "У этого КОТРАКТОРА нет собственности", заменил на "У данного контрагента пока отсутсвуют собственности. Создайте нажав кнопку 'Добавить собственность' "
* При удалении собственности в сообщении модального окна  "Собственность №30 будет удалена из списка навсегда. Вы уверены?" вместо #id отобразил наименование и госномер авто

refactor: Произвёл коррекцию детальной страницы контрагента

---

infrastructure/web/static/js/employee/employee_view.js
infrastructure/web/templates/employee/employees.html

Связано: #488
* Изменил заголовок "Список Сотрудников" на "Список сотрудников"
* Центрировал цифру номера страницы (задать параметры: width 100px и text-align: center)
* Вывел позицию сотрудника в формате bootstrap bage

refactor: Произвёл коррекцию страницы списка сотрудников

---

infrastructure/accounts/forms.py
infrastructure/accounts/validators.py
infrastructure/web/templates/registration/register.html

* Добавил валидации на длину, заглавную букву, на спец символ, на цифру.

fix: Написать валидацию на ввод логина и пароля при создании аккаунта

---

infrastructure/accounts/forms.py
infrastructure/accounts/validators.py
infrastructure/web/templates/registration/register.html

* Добавлена валидация на ввод логина

481 написать валидацию на ввод логина и пароля при создании аккаунта

---

infrastructure/web/own/views.py
infrastructure/web/static/js/own/own_view.js
infrastructure/web/templates/own/owns.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/urls.py
services/own_services.py

Связано: #468
* Добавлена страница списка всех собственностей
* Добавлена ссылка в сайдбар

feat: Добавлен вывод списка всех собственностей

---

infrastructure/web/templates/home.html

* Центрировал цифру номера страницы, В блоке поиска произвел локализацию (русификацию) полей выбора даты

fix: Коррекция страницы списка заказ-нарядов

---

infrastructure/web/employee/views.py
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/partials/employee/image_modal.html

* Вывод картинки в модальном окне.
* Скачивание фотографии.

fix: Подкорректировать детальную страницу сотрудника

---

infrastructure/web/templates/order/order_detail.html

Связано: #485
* Исправил опечатку
* Исправил вывод цены на гарантии

fix: Исправил опечатку и вывод цены на гарантии

---

infrastructure/web/templates/order/order_detail.html
requirements.txt

* Удалил pywin из requirements

коррекция страницы просмотра заказ наряда

---

infrastructure/accounts/views.py
infrastructure/web/static/css/style.css
infrastructure/web/templates/employee/employee_create.html
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/employee/employee_update.html
infrastructure/web/templates/partials/employee/employee_form.html
infrastructure/web/templates/registration/register.html
requirements.txt

* Скрыл поле Филиалы, и передал филиал из текущего филиала, к которому относится пользователь.
* На формах создания сотрудника (мастера и аккаунта) произвел локализацию (русификацию) поля файла
* Форму создания управляющего отобразил без поля загрузки файла уд.лич
* Уведомление Alert JS об успешном создании сотрудника заменил на Alert Sweet и расположил модальное окно в центре

fix: Коррекция создания сотрудника

---

infrastructure/web/order/views.py
infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/urls.py

Связано: #511
* Исправил создание заказ наряда от собственности контрактора

fix: Исправил создание заказ наряда от собственности контрактора

---

infrastructure/web/own/views.py
infrastructure/web/static/js/own/own_create.js
infrastructure/web/templates/partials/own/own_form.html

Связано: #498
* Исправил валидацию номера при создании автомобиля

fix: Исправил валидацию номера при создании автомобиля

---

core/settings.py
infrastructure/web/payment/context_processor.py
infrastructure/web/payment/forms.py
infrastructure/web/payment/views.py
infrastructure/web/static/js/order/order_list.js
infrastructure/web/templates/home.html
infrastructure/web/templates/partials/payment/payment_modal.html
infrastructure/web/urls.py

мастер дев 43

---

infrastructure/web/static/js/report/report_task_ajax.js

* изменил адрес подключения к вебсокетам для сервера

fix: изменил адрес подключения к вебсокетам для сервера

---

infrastructure/web/nomenclature/tests/test_nomenclature_views.py

Связано: #473
* Написал тесты для обновления номенклатуры

feat: Написал тесты для обновления номенклатуры

---

infrastructure/web/static/js/own/own_full_list.js
infrastructure/web/templates/own/owns.html

* Убрал кнопку детали контрагента в списке собственностей.
* Ccылку на детальную страницу контрагента указал наименование собственности

fix: Убрать кнопку детали контрагента в списке собственностей

---

infrastructure/web/trade_point/views.py

* После создания торговой точки поменял редирект на список торговых точек

fix: Поменять редирект на список филиалов при создании филиала

---

infrastructure/web/report/forms.py
infrastructure/web/report/views.py
infrastructure/web/static/js/report/report_task_ajax.js
infrastructure/web/templates/report/report.html
infrastructure/web/urls.py
services/report_services.py

Связано: #579
* Написать url для загрузки файла
* Написать формы для загрузки файла
* Написать шаблон для загрузки файла
* Обновить report_task_ajax.js для получения массива данных отчётов
* Описать логику контроллера для загрузки файла
* Создать файл сервисов report_services.py

feat: Реализовал скачивание отчётов Excel файлом

---

infrastructure/web/static/js/employee/employee_view.js

n
Связано: #560
* Исправил отображение ролей на странице списка сотрудников

fix: Исправил отображение ролей на странице списка сотрудников

---

infrastructure/web/contractor/views.py
infrastructure/web/static/js/contractor/contractor_view.js
infrastructure/web/static/js/own/own_full_list.js

Связано: #557
*  Исправил список контрагентов

fix: Исправил сипсок конрагентов

---

infrastructure/web/own/views.py
infrastructure/web/static/js/own/own_create.js
models/own/models.py

n
Связано: #558
*  Исправил валидацию при создании собственности

fix: Исправил валидацию при создании собственности

---

infrastructure/web/contractor/forms.py
infrastructure/web/contractor/views.py
infrastructure/web/templates/contractor/contractor_update_compare.html
infrastructure/web/templates/contractor/update.html
services/contractor_services.py
services/tests/test_contractor_services.py

feat: Исключил возможность редактирования ИИН/БИН контрагента

---

infrastructure/accounts/views.py
infrastructure/web/contractor/views.py
infrastructure/web/employee/views.py
infrastructure/web/nomenclature/views.py
infrastructure/web/order/views.py
infrastructure/web/trade_point/tests/test_trade_point.py
infrastructure/web/trade_point/views.py
services/employee_services.py
services/order_services.py
services/tests/test_trade_point_services.py
services/trade_point_services.py

Связано: #567
* Исправил селект трейд поинтов

fix: Исправил селект трейд поинтов

---

infrastructure/web/employee/views.py

Связано: #595
* Исправил создание сотрудника

fix: Исправил создание сотрудника

---

core/settings.py
infrastructure/web/employee/context_processor.py
infrastructure/web/nomenclature/views.py
infrastructure/web/static/js/own/own_list.js
infrastructure/web/templates/contractor/contractor_detail.html
infrastructure/web/templates/employee/employee_detail.html
infrastructure/web/templates/nomenclature/list.html
infrastructure/web/templates/order/order_detail.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/trade_point/trade_points.html

* Скрыл кнопки на которых у пользователей нет прав.

568 скрыть кнопки на которых у пользователей нет прав

---

infrastructure/web/order/views.py
infrastructure/web/templates/order/concurrency_update.html

Связано: #556
* Исправил логику расчёта стоимостей при параллельном обновлении
* Обновил шаблон

fix: Исправил конкурентное редактирование заказ наряда

---

infrastructure/web/employee/views.py
infrastructure/web/static/css/style.css
infrastructure/web/templates/employee/employee_update.html
infrastructure/web/templates/employee/employee_update_conflict.html
infrastructure/web/templates/partials/employee/employee_form.html

Связано: #561
* Реализован вывод изображения на странице редактирования данных мастера, также при оптимистичном блоке

fix: вывела фото при редактировании мастера и при отптимистик блоке

---

infrastructure/web/employee/views.py
infrastructure/web/templates/employee/employee_update_conflict.html
infrastructure/web/templates/partials/employee/employee_form.html

Связано: #604
* Починила возможность редактирования мастера без обязательного обновления фото

fix: исправила баг редактирования без фото

---

infrastructure/web/static/js/order/order_list.js
infrastructure/web/templates/order/order_detail.html

* Исправить вывод в детальной странице Заказ-наряда

fix: Исправить вывод в детальной странице Заказ-наряда

---

core/asgi.py
core/routing.py
core/settings.py
docker-compose.prod.yml
nginx/default.conf
requirements.txt

* Изменил конфигурацию nginx для подключения вебсокетов.
* Добавил новый сервер в docker-compose для запуска проекта через asgi.

fix: Исправить конфигурацию nginx для вебсокетов

---

infrastructure/web/context_processor.py
infrastructure/web/report/consumers.py
infrastructure/web/report/tasks.py
infrastructure/web/static/js/report/report_task_ajax.js
infrastructure/web/templates/base.html
infrastructure/web/templates/report/report.html
infrastructure/web/urls.py

исправить составление отчета

---

infrastructure/web/queue/views.py

fix: Исправил ошибки

---

models/queue/admin.py
models/queue/models.py

мастер дев 57

---

infrastructure/web/static/js/report/report_create.js
services/report_services.py

Связано: #634
* Обновить методы для получения массива данных отчёта в файле сервисов report_services.py

feat: Реализовал обновлённую логику скачивания отчёта в Excel файл

---

infrastructure/web/templates/partials/contractor/contractor_form.html

fix: ограничено количество символов в поле доверенного лица при вводу

---

infrastructure/web/payment/views.py
infrastructure/web/static/js/order/order_list.js
infrastructure/web/static/js/payment/pay_order.js
infrastructure/web/static/js/payment/pay_order_in_details.js
infrastructure/web/templates/order/order_detail.html
infrastructure/web/templates/partials/payment/payment_modal_detail.html

* добавить возможность произвести оплату в деталь стр заказ наряда

640 добавить возможность произвести оплату в деталь стр заказ наряда

---

infrastructure/web/order/signals.py
infrastructure/web/order/views.py
infrastructure/web/static/js/order/order_list.js
infrastructure/web/static/js/report/report_create.js
infrastructure/web/templates/home.html
infrastructure/web/urls.py
requirements.txt

Сввязано: #642
* Реализовал завершение заказ наряда

feat: Реализовал завершение заказ наряда

---

core/settings.py

* Изменены настройки логирования

fix: Изменены настройки уровня логирования

---

infrastructure/web/employee/views.py

Связано: #576
* Исправил ошибку при редактировании сотрудников

fix: Исправить ошибку при редактировании сотрудников

---

infrastructure/web/report/views.py
infrastructure/web/templates/report/report_detail.html
infrastructure/web/urls.py

Связано: #669
* Добавлено удаление отчета

feat: Реализовал удаление отчета

---

infrastructure/web/report/views.py
infrastructure/web/templates/report/report_detail.html
infrastructure/web/urls.py

мастер дев 68

---

infrastructure/web/templates/report/report_detail.html

мастер дев 69

---

infrastructure/web/employee/views.py
infrastructure/web/templates/partials/employee/employee_form.html

Связано: #675
* Исправил редактирование сотрудников

fix: Исправил редактирование сотрудников

---

infrastructure/web/employee/views.py
infrastructure/web/templates/partials/employee/employee_form.html

* Исправил создание сотрудника

исправить изменение сотрудников

---

infrastructure/web/static/js/own/own_full_list.js
infrastructure/web/templates/base.html
infrastructure/web/templates/contractor/update.html
infrastructure/web/templates/home.html
infrastructure/web/templates/nomenclature/list.html
infrastructure/web/templates/nomenclature/nomenclature_create.html
infrastructure/web/templates/order/order_create.html
infrastructure/web/templates/order/order_create_stage1.html
infrastructure/web/templates/order/order_create_stage2.html
infrastructure/web/templates/order/order_create_stage3.html
infrastructure/web/templates/order/order_create_stage4.html
infrastructure/web/templates/order/update.html
infrastructure/web/templates/own/own_create.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/queue/queue_create.html
infrastructure/web/templates/registration/login.html
infrastructure/web/templates/registration/register.html
infrastructure/web/templates/report/report.html
infrastructure/web/templates/report/report_detail.html
infrastructure/web/templates/report/report_list.html
infrastructure/web/templates/trade_point/trade_point_create.html
infrastructure/web/templates/trade_point/trade_point_update.html
infrastructure/web/templates/trade_point/trade_points.html
logs.log
models/contractor/validators.py

Связано: #682
* Исправил мелкие ошибки

fix: Исправил мелкие ошибки

---

infrastructure/web/static/js/own/own_full_list.js
infrastructure/web/templates/base.html
infrastructure/web/templates/contractor/update.html
infrastructure/web/templates/home.html
infrastructure/web/templates/nomenclature/list.html
infrastructure/web/templates/nomenclature/nomenclature_create.html
infrastructure/web/templates/order/order_create.html
infrastructure/web/templates/order/order_create_stage1.html
infrastructure/web/templates/order/order_create_stage2.html
infrastructure/web/templates/order/order_create_stage3.html
infrastructure/web/templates/order/order_create_stage4.html
infrastructure/web/templates/order/update.html
infrastructure/web/templates/own/own_create.html
infrastructure/web/templates/partials/sidebar.html
infrastructure/web/templates/queue/queue_create.html
infrastructure/web/templates/registration/login.html
infrastructure/web/templates/registration/register.html
infrastructure/web/templates/report/report.html
infrastructure/web/templates/report/report_detail.html
infrastructure/web/templates/report/report_list.html
infrastructure/web/templates/trade_point/trade_point_create.html
infrastructure/web/templates/trade_point/trade_point_update.html
infrastructure/web/templates/trade_point/trade_points.html
logs.log
models/contractor/validators.py

мастер дев 71

---

logs.log

fix: добавил логи чтобы при CI заново собрать образ celery

---

logs.log

мастер дев 73

---

infrastructure/web/report/consumers.py
infrastructure/web/report/views.py
infrastructure/web/static/js/report/report_create.js
infrastructure/web/templates/report/report.html

feat: Добавил кэширование отчета
